#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""siguard.py: Detecting Signature-related vulnerabilities
https://github.com/Siguard-Tool/Siguard
"""
from sys import exit
import siguard.interfaces.cli


if __name__ == "__main__":
    siguard.interfaces.cli.main()
    exit()

